-- MySQL Script generated by MySQL Workbench
-- Sun Nov  7 14:25:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema games_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema games_db
-- -----------------------------------------------------
CREATE DATABASE games_db;
CREATE SCHEMA IF NOT EXISTS `games_db` ;
USE `games_db` ;

-- -----------------------------------------------------
-- Table `games_db`.`console`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `games_db`.`console` (
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games_db`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `games_db`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `price` FLOAT NOT NULL,
  `stock` INT NULL,
  `console_name` VARCHAR(20) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `fk_productos_console_idx` (`console_name` ASC) VISIBLE,
  CONSTRAINT `fk_productos_console`
    FOREIGN KEY (`console_name`)
    REFERENCES `games_db`.`console` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games_db`.`usuariosCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `games_db`.`usuariosCategory` (
  `admin` TINYINT NOT NULL,
  PRIMARY KEY (`admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `games_db`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `usuariosCategory_admin` TINYINT NOT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `fk_usuarios_usuariosCategory1_idx` (`usuariosCategory_admin` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_usuariosCategory1`
    FOREIGN KEY (`usuariosCategory_admin`)
    REFERENCES `games_db`.`usuariosCategory` (`admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
